### ISSUE TITLE
Testing you methods on other modalities?

### ISSUE THREAD

**Issue by davidkvcs** [biomedia-mira/blast-ct#10]
Hi

Is my assessment correct, that your training pipeline does not allow to train on multimodality inputs, such as PET-CT?

I had shortlisted your method for testing on a large in-house annotated PET-CT head and neck cancer dataset I collected, however as far as I can see, your method only takes one modality as input.

Thanks in advance 

David

**Comment by davidkvcs** [comment]
Oh sorry, I just saw you are using DeepMedig, so I think this issue is solved by just going by https://github.com/deepmedic/deepmedic instead.
Although do let me know if you would suggest otherwise.

Sorry for disturbing.

**Comment by bglocker** [comment]
No worries. Thanks for your interest. I was just about to say to please check out DeepMedic as it provides support for multi-modal inputs.
