### ISSUE TITLE
Difference between certain location predictors?

### ISSUE THREAD

**Issue by meghutch** [biomedia-mira/blast-ct#16]
Thank you for the great package! When using the localization methods, what is the difference between the predictors such as: `prediction_iph_Cerebellum_ml`, `prediction_iph_LeftCerebellum_ml`, and `prediction_iph_RightCerebellum_ml` ? It doesn't seem that `prediction_iph_Cerebellum_ml` is the total of Left and Right, and is often much less. Is it the volume of blood that cannot be defined into Left and Right?

**Comment by bglocker** [comment]
Thank you for the kind feedback. Glad to hear the tool is useful.

All regions in the localisation module are distinct, non-overlapping. For cerebellum, there are three distinct regions with left, central, and right part of the cerebellum. So indeed, `prediction_iph_Cerebellum_ml` is not the combination of left and right, but it's own 'central' anatomical region.

Hope this makes sense.

**Comment by meghutch** [comment]
@bglocker Thank you so much for the quick response - this makes perfect sense!
