### ISSUE TITLE
Can ground truth segmentations be shared?

### ISSUE THREAD

**Issue by bartmch** [biomedia-mira/blast-ct#3]
Hi, I read your paper with great interest. Would it be possible to share the ground truth segmentations?

**Comment by MiguelMonteiro** [comment]
Hello, unfortunately I am not allowed to share the ground-truth segmentations or images myself, all data requests must follow the procedure described in the data-sharing section of the paper (located just before acknowledgments).

**Comment by bartmch** [comment]
Thank you, I'll follow the procedure.
