### ISSUE TITLE
How did you decide on patch size? How did you decide on step size to half lr?

### ISSUE THREAD

**Issue by bartmch** [biomedia-mira/blast-ct#4]
Hi! Just out of interest: How did you decide on what steps you should halve the learning rate (440, 640, 800, 900, 980, 1050)? Also, how did you decide on the patch size? Did you also try out different sizes?

Thanks!

**Comment by MiguelMonteiro** [comment]
Hello, the learning rate scheduler and patch size are basically the defaults or at least very small variations/adaptations of the original deepmedic [repo](https://github.com/deepmedic/deepmedic)
I did try different sizes (bigger size uses more memory and so you have to use smaller batch_size) but I don't have formal results for those experiments.
