### ISSUE TITLE
What is the sampling mask which model training needs?

### ISSUE THREAD

**Issue by whynopeoplefly** [biomedia-mira/blast-ct#6]
Hi! Thank you for sharing this great work.
I have a question about the sampling mask mentioned in "Training models on your own data" section.
How can we create this file? Is there any reference explaining the mask?
Thanks for the guidance.

**Comment by MiguelMonteiro** [comment]
The sampling mask is a binary map with the same size as the image which tells the program which parts of the image it can sample patches from. A "1" in the mask represents a voxel which can be sampled as a patch centre and a "0" is the opposite. In the case of blast-ct I use automatic generated brain masks by thresholding the CT scans between -15 and 100 HU.
