### ISSUE TITLE
Distribution of dataset slice thickness

### ISSUE THREAD

**Issue by chihchiehchen** [biomedia-mira/blast-ct#9]
Hello,

Thanks for implementing and sharing the code and pre-trained model. I have several brain CT scans with slice thickness 5mm, the pre-trained model outputs are mostly correct but there are some mistakes if we take care of more fine-grained details. Could I ask scans with which slice thickness  perform best in this model? 

Could I also ask the distribution of dataset slice thickness? Which slice thickness is most common in training dataset ?

If I work with scans with slice thickness 5mm, are there anything I shall take care of? I begin with dicom slices, merge them with dcm2nii (with the gantry tilt correction), and then follow the command in README.md.

Thanks for your patient and help!

**Comment by MiguelMonteiro** [comment]
Hi, the model tends to perform best in thick slice scans such as the ones you have. I don't know the distribution of slice thickness of the training set. Some mistkaes are to be expected for any deep learning model.
Seems like your preprocessing pipeline is correct.
